title: Department of Operations, University of Lausanne 
logo: unil.png
description: This page is to be used by the members of the Department of Operations at University of Lausanne, for the seminars in Statistics and Applied Probability, organised by [Valérie Chavez-Demoulin](https://hecnet.unil.ch/hec/recherche/fiche?pnom=vchavez&dyn_lang=fr), [Fabien Baeriswyl](https://fabienbaeriswyl.github.io) (from June 2021 onwards) and [Linda Mhalla](https://lindamhalla.netlify.app) (from June 2021 to July 2022).
theme: jekyll-theme-minimal
